backend:
  name: github
  repo: hidayahvibesbd/Hidayah-Vibes-Bd
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "hadith"
    label: "হাদিস"
    folder: "_hadith"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      
